# Generated by Django 4.1 on 2022-08-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_code', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qna',
            name='correct',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
