# Generated by Django 4.1 on 2022-08-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_code', '0002_game_score_qna_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='q_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
