# Generated by Django 4.1 on 2022-08-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_code', '0003_qna_q_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='free',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
